replicaCount: 3
image:
  repository: dimozone/vehicle-triggers-api
  pullPolicy: IfNotPresent
  tag: 1.1.17
env:
  ENVIRONMENT: prod
  PORT: '8080'
  MON_PORT: '8888'
  LOG_LEVEL: info
  DB_PORT: '5432'
  DB_NAME: vehicle_triggers_api
  DB_MAX_OPEN_CONNECTIONS: '100'
  DB_MAX_IDLE_CONNECTIONS: '30'
  SERVICE_NAME: vehicle-triggers-api
  JWK_KEY_SET_URL: https://auth.dimo.zone/keys
  IDENTITY_API_URL: https://identity-api.dimo.zone/query
  KAFKA_BROKERS: kafka-prod-dimo-kafka-kafka-brokers:9092
  TOKEN_EXCHANGE_GRPC_ADDR: token-exchange-api-prod:8086
  DIMO_REGISTRY_CHAIN_ID: 137
  VEHICLE_NFT_ADDRESS: '0xbA5738a18d83D41847dfFbDC6101d37C69c9B0cF'
  MAX_IN_FLIGHT: 50
  TOKEN_EXCHANGE_CACHE_EXPIRATION: 10m
  TOKEN_EXCHANGE_CACHE_CLEANUP_INTERVAL: 2m
ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/auth-tls-secret: ingress/cf-origin-ca
    nginx.ingress.kubernetes.io/auth-tls-verify-client: 'on'
    nginx.ingress.kubernetes.io/enable-cors: 'true'
    nginx.ingress.kubernetes.io/cors-allow-origin: '*'
    nginx.ingress.kubernetes.io/limit-rps: '9'
    external-dns.alpha.kubernetes.io/hostname: vehicle-triggers-api.dimo.zone
  hosts:
    - host: vehicle-triggers-api.dimo.zone
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
resources:
  limits:
    cpu: 1
    memory: 2048Mi
  requests:
    cpu: 250m
    memory: 1024Mi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
podDisruptionBudget:
  minAvailable: 1
